### ISSUE TITLE
missing vendor file?

### ISSUE THREAD

**Issue by jgrilo85** [BrandonDusseau/ics-display#3]
Hi there, getting this error and wondering if you are still around?

arning: require_once(/home/solut/public_html/cal/vendor/autoload.php): failed to open stream: No such file or directory in /home/solut/public_html/cal/schedule.php on line 3

Fatal error: require_once(): Failed opening required '/home/solut/public_html/cal/vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear') in /home/solut/public_html/cal/schedule.php on line 3

**Comment by BrandonDusseau** [comment]
Hello! It looks like you may have downloaded the source code instead of a [prepackaged release](https://github.com/BrandonDusseau/ics-display/releases/tag/v1.2.1). With the prepackaged releases, the dependencies are already downloaded and in place for you in the vendor directory.

If you're downloading the source for development purposes, you will need to [install Composer](https://getcomposer.org/download/) and then run the `composer install` command within the project directory. Otherwise, download the package I linked above and copy over the vendor folder into your installation.

Please let me know if this resolves your problem and I will close the issue.

**Comment by jgrilo85** [comment]
﻿Amazing! That did it!!

Thank you so much ☺

**Comment by BrandonDusseau** [comment]
No problem! I'm just glad to see someone's using something I wrote.
Enjoy!

**Comment by jgrilo85** [comment]
﻿Totally! We’ll make use of this.

www.solut.ca/cal<http://www.solut.ca/cal>

just need to play with the formatting and see if I can show all without scrolling. Like each date is its own column so to speak.

**Comment by jgrilo85** [comment]
﻿Hey Brandon, sorry do you mind another question please?

Could you look at our link

http://www.solut.ca/cal/

I’m not sure but the times listed in the event are off. Here is the source ICS URL.

http://app.wheniwork.com/calendar/036cef46df65a59618970fa788cf9ddc1a866459/global.ics

Server time is fine and correct. The ICS has the right times as well. Yet its rendered to the page weird?

**Comment by BrandonDusseau** [comment]
It appears PHP on your server is configured to use UTC time, which is the default. You could change this in your server's `php.ini`, but this can cause conflicts with other applications. In any case it is best practice to have the server time set to UTC.

I will create a release that adds the option to override the server time zone. The ICS parsing library is pretty out of date and could use a version bump anyway. Once I create the release, you'll be able to download it and copy over the new `vendor` folder and `schedule.php` file (though it would be better for you to update the entire thing and readd your style changes and `config.php`). At that point you can add `$timezone_override = "America/Denver";` (this is the time zone I saw in your ICS file, replace it at will) to your `config.php` file.

I'll update you when that is released.

**Comment by BrandonDusseau** [comment]
Updated! https://github.com/BrandonDusseau/ics-display/releases/tag/v1.2.2
Do note that due to changes in a library that my project depends on, the vendor directory is now much larger than before. If using FTP you may want to upload the zip to the server and extract it from there.

**Comment by jgrilo85** [comment]
Hey Brandon, once again thank you! i'm thankful you took time to help tweak and make this better! the timezone is good now!

www.solut.ca/cal<http://www.solut.ca/cal>

Next i'm going to try and play with trying to not even show past events. I have days_back to 0 but even today (morning shifts) i would like to disappear and free up space for future events.

I think all i need to do is tweak the schedule.php file. If you have a suggestion or know a quick way please let me know 🙂
________________________________

Jason Grilo
NOC Manager
Office: 780.229.1990 Ext. 780-229-1968
10205 - 101 Street NW, Suite No. 401 
Edmonton, AB T5J 4H5
People
•
Insight
•
Tech
solut.ca

**Comment by BrandonDusseau** [comment]
You _should_ be able to just add `if (strtotime($event->dtstart) < strtotime("now")) { continue; }` at line 32 of schedule.php. Theoretically that will cause it to skip any events in the past. If you want to get fancy you can add an option for it to your config file and toss that onto the beginning of the if condition.

**Comment by BrandonDusseau** [comment]
By the way, I notice you've got all events highlighted. Is that intentional? The example config has `$highlight_calendars` enabled by default. If you don't want everything highlighted, I recommend setting that value to `false`. Perhaps you could make use of the `$highlight_keyword` value for on-call events.

**Comment by jgrilo85** [comment]
Ah yes, i changed it and its white now. Ok i'll use that instead.

I tried your if statement at line 32 of schedule.php but it didn't really like it. Just nothing loaded.

I guess for our use we have morning shifts and afternoon shifts so once we are in the PM we don't need to see who was in the AM.
________________________________

Jason Grilo
NOC Manager
Office: 780.229.1990 Ext. 780-229-1968
10205 - 101 Street NW, Suite No. 401 
Edmonton, AB T5J 4H5
People
•
Insight
•
Tech
solut.ca

**Comment by BrandonDusseau** [comment]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/3901864/61250703-64029f00-a726-11e9-9c26-1d5d79482521.png">
It seems to work for me locally. Any errors in your server's PHP log? What happens if you go to /schedule.php in the browser?

**Comment by jgrilo85** [comment]
So i have this on line 32

$this_ical = new \ICal\ICal($url);

Is the line of code you gave me, replace that line or put that inside the IF?
________________________________

Jason Grilo
NOC Manager
Office: 780.229.1990 Ext. 780-229-1968
10205 - 101 Street NW, Suite No. 401 
Edmonton, AB T5J 4H5
People
•
Insight
•
Tech
solut.ca

**Comment by BrandonDusseau** [comment]
Ah, you must have made more changes than I thought to that file. Just add it immediately after the `foreach($events ...` line as shown in the screenshot.

**Comment by jgrilo85** [comment]
totally my fault! i must have missed overwritting schedule.php and it was from the previous version.

sorry i got it now! - i commented it out so can flip it on and off and need.
________________________________

Jason Grilo
NOC Manager
Office: 780.229.1990 Ext. 780-229-1968
10205 - 101 Street NW, Suite No. 401 
Edmonton, AB T5J 4H5
People
•
Insight
•
Tech
solut.ca
